# Lorena Espeche

### Verbo GET – listar todos
GET http://localhost:8000/funcionario/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/funcionario/10 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1
content-type: application/json

{
    "nome" : "Lorena",
    "matricula" : "7747",
    "cpf" : "1",
    "telefone" : "4912341234",
    "grupo" : 1,
    "senha" : "9Sg9K8I7g4oC"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/funcionario/2 HTTP/1.1
content-type: application/json

{
    "nome" : "Lorena",
    "matricula" : "7747",
    "cpf" : "1",
    "telefone" : "4912341234",
    "grupo" : 1,
    "senha" : "n99S2rfBvpl9"   
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/funcionario/3 HTTP/1.1